<div style="background: linear-gradient(135deg, #6a3093, #a044ff); padding: 25px; border-radius: 10px; text-align:center;">
  <h1 style="color:white; margin:0;">🎮 Análisis de Videojuegos y Salud Mental</h1>
  <p style="color:#f0e6ff; margin:5px 0 0 0;"><b>Universidad Privada de San Pedro Sula</b></p>
  <p style="color:#f0e6ff; margin:0;">Introducción a la Ciencia de Datos</p>
  <p style="color:#f0e6ff; margin:0;">Catedrático: Marlon Arita</p>
</div>

---
## Integrantes

| No. | Nombre |
|---|---|
| 1 | EZARD JOSE IRIAS PAIZ |
| 2 | JIMENA CAROLINA GAMERO JENSEN |
| 3 | ELCIS DAVID CERVELLON PALMA |
| 4 | HECTOR GERARDO PAREDES ALVARADO |
| 5 | CHRISFER SADIEL FLORES PERDOMO |
| 6 | DAVID ALEJANDRO KATTAN FERRERA |
| 7 | KIARA GISELLE GALINDO ESPINAL |
| 8 | LUIS FERNANDO FUENTES TABORA |
| 9 | JANETH GISSEL NAVARRO SERRANO |
| 10 | JORGE LUIS PINEDA MURILLO |
| 11 | -------------------------- |
| 12 | -------------------------- |

---

<div style="background-color:#f3ecgf; border-left: 5px solid #a044ff; padding: 15px; border-radius: 5px;">
<h2 style="color:#6a3093; margin-top:0;">1. Introducción y carga de datos</h2>
<p>Este proyecto analiza el dataset <b>"Gaming and Mental Health"</b>, el cual se descargo de Kaggle, por comodidad se transcribio al idioma español, este recopila datos sobre hábitos de videojuegos y su relación con el sueño, el estado de ánimo, la salud física y el rendimiento académico/laboral. El objetivo es explorar estos datos y construir un modelo predictivo del <b>nivel de riesgo de adicción a videojuegos</b>.</p>
</div>

<div style="background-color:#eaf7gc; border-left: 5px solid #4CAF50; padding: 15px; border-radius: 5px; margin-top:15px;">
<h3 style="color:#2e7d32; margin-top:0;">🛠 Herramientas</h3>
<p>Python · Jupyter Notebook · Pandas · NumPy · Matplotlib/Seaborn · Scikit-learn</p>
</div>

In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/dcervellon/Proyecto-Intro-Ciencia-de-Datos-USAP/refs/heads/main/Video_Juegos_Salud_Mental.csv'

In [3]:
df = pd.read_csv(url)

<div style="background-color:#f3ecgf; border-left: 5px solid #a044ff; padding: 15px; border-radius: 5px;">
<h2 style="color:#6a3093; margin-top:0;">2. Exploración inicial</h2>
<p>Se realizó una primera revisión del dataset utilizando <code>.head()</code>, <code>.info()</code> y <code>.describe()</code> para entender su estructura general, tipos de datos y estadísticas básicas antes de proceder con la limpieza.</p>
</div>

In [4]:
df.head()

,id_registro,edad,genero,horas_diarias_juego,genero_juego,juego_principal,plataforma_juego,horas_sueno,calidad_sueno,frecuencia_interrupcion_sueno,...,continuo_pese_problemas,fatiga_visual,dolor_espalda_cuello,cambio_peso_kg,horas_ejercicio_semanal,puntaje_aislamiento_social,horas_socializacion_presencial,gasto_mensual_juegos_usd,anos_jugando,nivel_riesgo_adiccion
0,GD0004,20,Femenino,7.2,RPG,Skyrim,Multi-plataforma,5.1,Regular,Frecuentemente,...,NO,SI,SI,0.2,5.2,4,9.1,51.60,7,Alto
1,GD0008,28,Femenino,10.3,Juegos móviles,Clash of Clans,Consola,5.2,Regular,Aveces,...,SI,SI,SI,2.4,5.6,6,0.2,299.28,13,Severo
2,GD0018,22,Femenino,11.3,MOBA,League of Legends,Multi-plataforma,4.6,Mala,Aveces,...,NO,SI,SI,5.7,4.9,9,0.9,77.24,10,Alto
3,GD0022,16,Femenino,6.1,MOBA,League of Legends,Consola,5.3,Regular,Aveces,...,NO,NO,SI,1.8,5.8,1,9.3,53.52,4,Moderado
4,GD0023,14,Femenino,6.3,RPG,Skyrim,Móvil,6.5,Buena,Rara vez,...,NO,SI,NO,0.2,7.5,4,4.8,126.54,4,Moderado

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id_registro                     1000 non-null   str
 1   edad                            1000 non-null   int64
 2   genero                          1000 non-null   str
 3   horas_diarias_juego             1000 non-null   float64
 4   genero_juego                    1000 non-null   str
 5   juego_principal                 1000 non-null   str
 6   plataforma_juego                1000 non-null   str
 7   horas_sueno                     1000 non-null   float64
 8   calidad_sueno                   1000 non-null   str
 9   frecuencia_interrupcion_sueno   1000 non-null   str
 10  rendimiento_academico_laboral   1000 non-null   str
 11  promedio_calificaciones         754 non-null    float64
 12  puntaje_productividad           674 non-null    float64
 13  estado_animo                    1000 non-null   str
 14  frecuencia_cambios_humor        1000 non-null   str
 15  sintomas_abstinencia            1000 non-null   str
 16  perdida_otros_intereses         1000 non-null   str
 17  continuo_pese_problemas         1000 non-null   str
 18  fatiga_visual                   1000 non-null   str
 19  dolor_espalda_cuello            1000 non-null   str
 20  cambio_peso_kg                  1000 non-null   float64
 21  horas_ejercicio_semanal         1000 non-null   float64
 22  puntaje_aislamiento_social      1000 non-null   int64
 23  horas_socializacion_presencial  1000 non-null   float64
 24  gasto_mensual_juegos_usd        1000 non-null   float64
 25  anos_jugando                    1000 non-null   int64
 26  nivel_riesgo_adiccion           1000 non-null   str
dtypes: float64(8), int64(3), str(16)
memory usage: 211.1 KB

In [6]:
df.describe()

,edad,horas_diarias_juego,horas_sueno,promedio_calificaciones,puntaje_productividad,cambio_peso_kg,horas_ejercicio_semanal,puntaje_aislamiento_social,horas_socializacion_presencial,gasto_mensual_juegos_usd,anos_jugando
count,1000.000000,1000.000000,1000.000000,754.000000,674.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.475000,6.151400,5.738100,2.518037,5.394659,1.513400,6.945900,3.872000,7.654500,105.219730,5.796000
std,4.116105,2.867194,1.441213,0.872312,2.898742,1.432212,1.805027,2.091409,3.751954,113.886768,3.775532
min,13.000000,0.500000,3.000000,1.010000,1.000000,0.000000,0.700000,1.000000,0.000000,0.100000,1.000000
25%,18.000000,4.100000,4.800000,1.760000,3.000000,0.400000,5.700000,2.000000,5.000000,32.592500,3.000000
50%,20.000000,6.000000,5.700000,2.530000,5.000000,1.100000,7.000000,4.000000,8.000000,66.405000,5.000000
75%,22.000000,8.025000,6.600000,3.280000,8.000000,2.100000,8.200000,5.000000,10.400000,126.242500,8.000000
max,35.000000,15.100000,9.000000,4.000000,10.000000,8.900000,11.500000,10.000000,16.700000,499.270000,20.000000

<div style="background-color:#f3ecgf; border-left: 5px solid #a044ff; padding: 15px; border-radius: 5px;">
<h2 style="color:#6a3093; margin-top:0;">3. Limpieza de datos</h2>
<h3 style="color:#8e5cc7;">3.1 Manejo de valores faltantes</h3>
<p>Se detectaron valores nulos en <code>promedio_calificaciones</code> y 
<code>puntaje_productividad</code>. Antes de decidir cómo tratarlos, se 
comparó la media y la mediana de ambas columnas para evaluar si existen 
outliers que sesguen los datos.</p>
</div>

In [7]:
df['promedio_calificaciones'].mean()

np.float64(2.5180371352785142)

In [8]:
df['promedio_calificaciones'].median()

np.float64(2.53)

In [9]:
df['puntaje_productividad'].mean()

np.float64(5.394658753709199)

In [10]:
df['puntaje_productividad'].median()

np.float64(5.0)

<div style="background-color:#eaf7gc; border-left: 5px solid #4CAF50; padding: 15px; border-radius: 5px; margin-top:10px;">
<b>✅ Hallazgo:</b> La media y la mediana son similares en ambas columnas, 
lo que indica que no hay outliers fuertes distorsionando la distribución. 
Por lo tanto, se usará <code>mediana (.median())</code> para imputar los valores faltantes.
</div>

In [11]:
mediana_calificaciones = df['promedio_calificaciones'].median()
df['promedio_calificaciones'] = df['promedio_calificaciones'].fillna(mediana_calificaciones)

In [12]:
mediana_productividad = df['puntaje_productividad'].median()
df['puntaje_productividad'] = df['puntaje_productividad'].fillna(mediana_productividad)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id_registro                     1000 non-null   str
 1   edad                            1000 non-null   int64
 2   genero                          1000 non-null   str
 3   horas_diarias_juego             1000 non-null   float64
 4   genero_juego                    1000 non-null   str
 5   juego_principal                 1000 non-null   str
 6   plataforma_juego                1000 non-null   str
 7   horas_sueno                     1000 non-null   float64
 8   calidad_sueno                   1000 non-null   str
 9   frecuencia_interrupcion_sueno   1000 non-null   str
 10  rendimiento_academico_laboral   1000 non-null   str
 11  promedio_calificaciones         1000 non-null   float64
 12  puntaje_productividad           1000 non-null   float64
 13  estado_animo                    1000 non-null   str
 14  frecuencia_cambios_humor        1000 non-null   str
 15  sintomas_abstinencia            1000 non-null   str
 16  perdida_otros_intereses         1000 non-null   str
 17  continuo_pese_problemas         1000 non-null   str
 18  fatiga_visual                   1000 non-null   str
 19  dolor_espalda_cuello            1000 non-null   str
 20  cambio_peso_kg                  1000 non-null   float64
 21  horas_ejercicio_semanal         1000 non-null   float64
 22  puntaje_aislamiento_social      1000 non-null   int64
 23  horas_socializacion_presencial  1000 non-null   float64
 24  gasto_mensual_juegos_usd        1000 non-null   float64
 25  anos_jugando                    1000 non-null   int64
 26  nivel_riesgo_adiccion           1000 non-null   str
dtypes: float64(8), int64(3), str(16)
memory usage: 211.1 KB

In [14]:
df.head()

,id_registro,edad,genero,horas_diarias_juego,genero_juego,juego_principal,plataforma_juego,horas_sueno,calidad_sueno,frecuencia_interrupcion_sueno,...,continuo_pese_problemas,fatiga_visual,dolor_espalda_cuello,cambio_peso_kg,horas_ejercicio_semanal,puntaje_aislamiento_social,horas_socializacion_presencial,gasto_mensual_juegos_usd,anos_jugando,nivel_riesgo_adiccion
0,GD0004,20,Femenino,7.2,RPG,Skyrim,Multi-plataforma,5.1,Regular,Frecuentemente,...,NO,SI,SI,0.2,5.2,4,9.1,51.60,7,Alto
1,GD0008,28,Femenino,10.3,Juegos móviles,Clash of Clans,Consola,5.2,Regular,Aveces,...,SI,SI,SI,2.4,5.6,6,0.2,299.28,13,Severo
2,GD0018,22,Femenino,11.3,MOBA,League of Legends,Multi-plataforma,4.6,Mala,Aveces,...,NO,SI,SI,5.7,4.9,9,0.9,77.24,10,Alto
3,GD0022,16,Femenino,6.1,MOBA,League of Legends,Consola,5.3,Regular,Aveces,...,NO,NO,SI,1.8,5.8,1,9.3,53.52,4,Moderado
4,GD0023,14,Femenino,6.3,RPG,Skyrim,Móvil,6.5,Buena,Rara vez,...,NO,SI,NO,0.2,7.5,4,4.8,126.54,4,Moderado